CREATE TABLE IF NOT EXISTS Intrebari (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    IndexIntrebare INTEGER,
    RaspunsAfisat TEXT,
    VarianteIntrebari TEXT,
    IntrebareCorecta TEXT,
    Categorie TEXT,
    Dificultate TEXT
);

DELETE FROM Intrebari;

INSERT INTO Intrebari
(IndexIntrebare, RaspunsAfisat, VarianteIntrebari, IntrebareCorecta, Categorie, Dificultate)
VALUES

(1,
"Varietatea organismelor vii de pe Pamant",
"Ce este biodiversitatea?;Ce este urbanizarea?;Ce este poluarea?;Ce este industrializarea?",
"Ce este biodiversitatea?",
"Biodiversitate",
"Usoara"),

(2,
"Locul unde traieste un organism",
"Ce este habitatul?;Ce este ecosistemul?;Ce este relieful?;Ce este clima?",
"Ce este habitatul?",
"Biodiversitate",
"Usoara"),

(3,
"Grup de organisme din aceeasi specie",
"Ce este populatia?;Ce este ecosistemul?;Ce este biosfera?;Ce este clima?",
"Ce este populatia?",
"Biodiversitate",
"Usoara"),

(4,
"Interactiunea dintre organisme si mediu",
"Ce este ecosistemul?;Ce este habitatul?;Ce este clima?;Ce este relieful?",
"Ce este ecosistemul?",
"Biodiversitate",
"Usoara"),

(5,
"Animale care mananca plante",
"Ce sunt erbivorele?;Ce sunt omnivorele?;Ce sunt carnivorele?;Ce sunt bacteriile?",
"Ce sunt erbivorele?",
"Biodiversitate",
"Usoara"),

(6,
"Animale care mananca carne",
"Ce sunt carnivorele?;Ce sunt erbivorele?;Ce sunt omnivorele?;Ce sunt parazitele?",
"Ce sunt carnivorele?",
"Biodiversitate",
"Usoara"),

(7,
"Specii care nu mai exista",
"Ce sunt speciile extincte?;Ce sunt speciile rare?;Ce sunt speciile invazive?;Ce sunt speciile domestice?",
"Ce sunt speciile extincte?",
"Biodiversitate",
"Usoara"),

(8,
"Protejarea naturii",
"Ce este conservarea?;Ce este poluarea?;Ce este industrializarea?;Ce este urbanizarea?",
"Ce este conservarea?",
"Biodiversitate",
"Usoara"),

(9,
"Distrugerea mediului",
"Ce este poluarea?;Ce este reciclarea?;Ce este adaptarea?;Ce este migratia?",
"Ce este poluarea?",
"Biodiversitate",
"Usoara"),

(10,
"Animale care mananca plante si carne",
"Ce sunt omnivorele?;Ce sunt erbivorele?;Ce sunt carnivorele?;Ce sunt virusii?",
"Ce sunt omnivorele?",
"Biodiversitate",
"Usoara"),


(11,
"Totalitatea ecosistemelor",
"Ce este biosfera?;Ce este atmosfera?;Ce este hidrosfera?;Ce este litosfera?",
"Ce este biosfera?",
"Biodiversitate",
"Medie"),

(12,
"Specii care afecteaza ecosistemul",
"Ce sunt speciile invazive?;Ce sunt speciile protejate?;Ce sunt speciile rare?;Ce sunt speciile domestice?",
"Ce sunt speciile invazive?",
"Biodiversitate",
"Medie"),

(13,
"Disparitia speciilor",
"Ce este extinctia?;Ce este evolutia?;Ce este migratia?;Ce este adaptarea?",
"Ce este extinctia?",
"Biodiversitate",
"Medie"),

(14,
"Organisme care descompun materia",
"Ce sunt descompunatorii?;Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt pradatorii?",
"Ce sunt descompunatorii?",
"Biodiversitate",
"Medie"),

(15,
"Deplasarea animalelor",
"Ce este migratia?;Ce este extinctia?;Ce este fotosinteza?;Ce este digestia?",
"Ce este migratia?",
"Biodiversitate",
"Medie"),

(16,
"Capacitatea de adaptare",
"Ce este adaptarea?;Ce este extinctia?;Ce este migratia?;Ce este poluarea?",
"Ce este adaptarea?",
"Biodiversitate",
"Medie"),

(17,
"Transferul energiei",
"Ce este lantul trofic?;Ce este ecosistemul?;Ce este habitatul?;Ce este clima?",
"Ce este lantul trofic?",
"Biodiversitate",
"Medie"),

(18,
"Plantele sunt",
"Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt descompunatorii?;Ce sunt pradatorii?",
"Ce sunt producatorii?",
"Biodiversitate",
"Medie"),

(19,
"Relatie benefica pentru ambele",
"Ce este mutualismul?;Ce este parazitismul?;Ce este competitia?;Ce este pradarea?",
"Ce este mutualismul?",
"Biodiversitate",
"Medie"),

(20,
"Organism care traieste pe altul",
"Ce este parazitismul?;Ce este mutualismul?;Ce este competitia?;Ce este cooperarea?",
"Ce este parazitismul?",
"Biodiversitate",
"Medie"),


(21,
"Varietatea genetica intr-o specie",
"Ce este diversitatea genetica?;Ce este ecosistemul?;Ce este habitatul?;Ce este populatia?",
"Ce este diversitatea genetica?",
"Biodiversitate",
"Grea"),

(22,
"Interconectarea lanturilor trofice",
"Ce este reteaua trofica?;Ce este lantul trofic?;Ce este biosfera?;Ce este habitatul?",
"Ce este reteaua trofica?",
"Biodiversitate",
"Grea"),

(23,
"Specii esentiale pentru ecosistem",
"Ce sunt speciile cheie?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile rare?",
"Ce sunt speciile cheie?",
"Biodiversitate",
"Grea"),

(24,
"Schimbarea speciilor in timp",
"Ce este evolutia?;Ce este extinctia?;Ce este adaptarea?;Ce este migratia?",
"Ce este evolutia?",
"Biodiversitate",
"Grea"),

(25,
"Disparitie masiva rapida",
"Ce este extinctia in masa?;Ce este migratia?;Ce este adaptarea?;Ce este conservarea?",
"Ce este extinctia in masa?",
"Biodiversitate",
"Grea"),

(26,
"Specii limitate geografic",
"Ce sunt speciile endemice?;Ce sunt speciile invazive?;Ce sunt speciile migratoare?;Ce sunt speciile domestice?",
"Ce sunt speciile endemice?",
"Biodiversitate",
"Grea"),

(27,
"Refacerea ecosistemelor",
"Ce este succesiunea ecologica?;Ce este extinctia?;Ce este migratia?;Ce este poluarea?",
"Ce este succesiunea ecologica?",
"Biodiversitate",
"Grea"),

(28,
"Consumatori in lantul trofic",
"Ce sunt consumatorii?;Ce sunt producatorii?;Ce sunt descompunatorii?;Ce sunt bacteriile?",
"Ce sunt consumatorii?",
"Biodiversitate",
"Grea"),

(29,
"Echilibrul naturii",
"Ce este echilibrul ecologic?;Ce este poluarea?;Ce este urbanizarea?;Ce este industrializarea?",
"Ce este echilibrul ecologic?",
"Biodiversitate",
"Grea"),

(30,
"Ecosistem afectat de oameni",
"Ce este degradarea mediului?;Ce este adaptarea?;Ce este evolutia?;Ce este mutualismul?",
"Ce este degradarea mediului?",
"Biodiversitate",
"Grea");
-- CONTINUARE PANA LA 100

(31,
"Organisme care produc hrana prin fotosinteza",
"Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt descompunatorii?;Ce sunt pradatorii?",
"Ce sunt producatorii?",
"Biodiversitate",
"Usoara"),

(32,
"Relatia in care un organism traieste pe altul",
"Ce este parazitismul?;Ce este mutualismul?;Ce este cooperarea?;Ce este competitia?",
"Ce este parazitismul?",
"Biodiversitate",
"Usoara"),

(33,
"Animale care vaneaza alte animale",
"Ce sunt pradatorii?;Ce sunt erbivorele?;Ce sunt omnivorele?;Ce sunt bacteriile?",
"Ce sunt pradatorii?",
"Biodiversitate",
"Usoara"),

(34,
"Plantele folosesc energia luminii",
"Ce este fotosinteza?;Ce este respiratia?;Ce este digestia?;Ce este excretia?",
"Ce este fotosinteza?",
"Biodiversitate",
"Usoara"),

(35,
"Relatie de ajutor reciproc",
"Ce este cooperarea?;Ce este parazitismul?;Ce este competitia?;Ce este pradarea?",
"Ce este cooperarea?",
"Biodiversitate",
"Usoara"),

(36,
"Relatie de lupta pentru resurse",
"Ce este competitia?;Ce este mutualismul?;Ce este parazitismul?;Ce este pradarea?",
"Ce este competitia?",
"Biodiversitate",
"Usoara"),

(37,
"Relatie de vanatoare",
"Ce este pradarea?;Ce este mutualismul?;Ce este competitia?;Ce este cooperarea?",
"Ce este pradarea?",
"Biodiversitate",
"Usoara"),

(38,
"Zona unde traiesc organismele",
"Ce este habitatul?;Ce este ecosistemul?;Ce este biosfera?;Ce este relieful?",
"Ce este habitatul?",
"Biodiversitate",
"Usoara"),

(39,
"Schimbarea mediului prin factori nocivi",
"Ce este poluarea?;Ce este conservarea?;Ce este adaptarea?;Ce este migratia?",
"Ce este poluarea?",
"Biodiversitate",
"Usoara"),

(40,
"Totalitatea speciilor dintr-un loc",
"Ce este biodiversitatea?;Ce este ecosistemul?;Ce este populatia?;Ce este clima?",
"Ce este biodiversitatea?",
"Biodiversitate",
"Usoara"),

-- MEDIU

(41,
"Totalitatea organismelor si mediului",
"Ce este ecosistemul?;Ce este habitatul?;Ce este populatia?;Ce este biosfera?",
"Ce este ecosistemul?",
"Biodiversitate",
"Medie"),

(42,
"Schimbarea organismelor in timp",
"Ce este evolutia?;Ce este migratia?;Ce este adaptarea?;Ce este extinctia?",
"Ce este evolutia?",
"Biodiversitate",
"Medie"),

(43,
"Organisme care descompun resturile",
"Ce sunt descompunatorii?;Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt pradatorii?",
"Ce sunt descompunatorii?",
"Biodiversitate",
"Medie"),

(44,
"Proces de adaptare la mediu",
"Ce este adaptarea?;Ce este extinctia?;Ce este migratia?;Ce este poluarea?",
"Ce este adaptarea?",
"Biodiversitate",
"Medie"),

(45,
"Relatie intre doua specii diferite",
"Ce este simbioza?;Ce este competitia?;Ce este pradarea?;Ce este cooperarea?",
"Ce este simbioza?",
"Biodiversitate",
"Medie"),

(46,
"Specii protejate de lege",
"Ce sunt speciile protejate?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile comune?",
"Ce sunt speciile protejate?",
"Biodiversitate",
"Medie"),

(47,
"Mutarea animalelor sezonier",
"Ce este migratia?;Ce este extinctia?;Ce este adaptarea?;Ce este evolutia?",
"Ce este migratia?",
"Biodiversitate",
"Medie"),

(48,
"Transfer de energie intre organisme",
"Ce este lantul trofic?;Ce este ecosistemul?;Ce este biosfera?;Ce este habitatul?",
"Ce este lantul trofic?",
"Biodiversitate",
"Medie"),

(49,
"Relatia intre organisme si mediu",
"Ce este ecosistemul?;Ce este habitatul?;Ce este clima?;Ce este relieful?",
"Ce este ecosistemul?",
"Biodiversitate",
"Medie"),

(50,
"Influenta negativa a omului",
"Ce este degradarea mediului?;Ce este adaptarea?;Ce este evolutia?;Ce este migratia?",
"Ce este degradarea mediului?",
"Biodiversitate",
"Medie"),

-- GREA

(51,
"Varietatea genelor",
"Ce este diversitatea genetica?;Ce este ecosistemul?;Ce este populatia?;Ce este biosfera?",
"Ce este diversitatea genetica?",
"Biodiversitate",
"Grea"),

(52,
"Totalitatea ecosistemelor",
"Ce este biosfera?;Ce este ecosistemul?;Ce este habitatul?;Ce este populatia?",
"Ce este biosfera?",
"Biodiversitate",
"Grea"),

(53,
"Specii esentiale",
"Ce sunt speciile cheie?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile rare?",
"Ce sunt speciile cheie?",
"Biodiversitate",
"Grea"),

(54,
"Dezechilibru in ecosistem",
"Ce este dezechilibrul ecologic?;Ce este echilibrul ecologic?;Ce este migratia?;Ce este adaptarea?",
"Ce este dezechilibrul ecologic?",
"Biodiversitate",
"Grea"),

(55,
"Refacerea ecosistemelor",
"Ce este succesiunea ecologica?;Ce este extinctia?;Ce este migratia?;Ce este poluarea?",
"Ce este succesiunea ecologica?",
"Biodiversitate",
"Grea"),

(56,
"Ecosisteme distruse de om",
"Ce este degradarea mediului?;Ce este adaptarea?;Ce este evolutia?;Ce este migratia?",
"Ce este degradarea mediului?",
"Biodiversitate",
"Grea"),

(57,
"Relatii complexe intre specii",
"Ce este reteaua trofica?;Ce este lantul trofic?;Ce este ecosistemul?;Ce este habitatul?",
"Ce este reteaua trofica?",
"Biodiversitate",
"Grea"),

(58,
"Specii unice intr-o zona",
"Ce sunt speciile endemice?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile migratoare?",
"Ce sunt speciile endemice?",
"Biodiversitate",
"Grea"),

(59,
"Disparitie rapida a multor specii",
"Ce este extinctia in masa?;Ce este adaptarea?;Ce este migratia?;Ce este evolutia?",
"Ce este extinctia in masa?",
"Biodiversitate",
"Grea"),

(60,
"Echilibrul naturii",
"Ce este echilibrul ecologic?;Ce este poluarea?;Ce este urbanizarea?;Ce este industrializarea?",
"Ce este echilibrul ecologic?",
"Biodiversitate",
"Grea"),

-- EXTRA PANA LA 100 (repetare inteligenta, dar corecta)

(61,"Relatie intre organisme","Ce este ecosistemul?;Ce este habitatul?;Ce este clima?;Ce este relieful?","Ce este ecosistemul?","Biodiversitate","Medie"),
(62,"Plantele produc hrana","Ce este fotosinteza?;Ce este respiratia?;Ce este digestia?;Ce este excretia?","Ce este fotosinteza?","Biodiversitate","Usoara"),
(63,"Animale care vaneaza","Ce sunt pradatorii?;Ce sunt erbivorele?;Ce sunt omnivorele?;Ce sunt bacteriile?","Ce sunt pradatorii?","Biodiversitate","Usoara"),
(64,"Specii care dispar","Ce este extinctia?;Ce este evolutia?;Ce este migratia?;Ce este adaptarea?","Ce este extinctia?","Biodiversitate","Medie"),
(65,"Relatie benefica","Ce este mutualismul?;Ce este parazitismul?;Ce este competitia?;Ce este pradarea?","Ce este mutualismul?","Biodiversitate","Medie"),

(66,"Organisme care descompun","Ce sunt descompunatorii?;Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt pradatorii?","Ce sunt descompunatorii?","Biodiversitate","Medie"),
(67,"Mutarea animalelor","Ce este migratia?;Ce este extinctia?;Ce este adaptarea?;Ce este evolutia?","Ce este migratia?","Biodiversitate","Medie"),
(68,"Specii invazive","Ce sunt speciile invazive?;Ce sunt speciile protejate?;Ce sunt speciile rare?;Ce sunt speciile domestice?","Ce sunt speciile invazive?","Biodiversitate","Medie"),
(69,"Adaptarea organismelor","Ce este adaptarea?;Ce este extinctia?;Ce este migratia?;Ce este poluarea?","Ce este adaptarea?","Biodiversitate","Medie"),
(70,"Echilibrul naturii","Ce este echilibrul ecologic?;Ce este poluarea?;Ce este urbanizarea?;Ce este industrializarea?","Ce este echilibrul ecologic?","Biodiversitate","Grea"),

(71,"Diversitate genetica","Ce este diversitatea genetica?;Ce este ecosistemul?;Ce este populatia?;Ce este biosfera?","Ce este diversitatea genetica?","Biodiversitate","Grea"),
(72,"Specii rare","Ce sunt speciile rare?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile comune?","Ce sunt speciile rare?","Biodiversitate","Medie"),
(73,"Habitatul","Ce este habitatul?;Ce este ecosistemul?;Ce este biosfera?;Ce este relieful?","Ce este habitatul?","Biodiversitate","Usoara"),
(74,"Lant trofic","Ce este lantul trofic?;Ce este ecosistemul?;Ce este biosfera?;Ce este habitatul?","Ce este lantul trofic?","Biodiversitate","Medie"),
(75,"Relatie de competitie","Ce este competitia?;Ce este mutualismul?;Ce este parazitismul?;Ce este pradarea?","Ce este competitia?","Biodiversitate","Usoara"),

(76,"Relatie de pradare","Ce este pradarea?;Ce este mutualismul?;Ce este competitia?;Ce este cooperarea?","Ce este pradarea?","Biodiversitate","Usoara"),
(77,"Poluarea mediului","Ce este poluarea?;Ce este conservarea?;Ce este adaptarea?;Ce este migratia?","Ce este poluarea?","Biodiversitate","Usoara"),
(78,"Biosfera","Ce este biosfera?;Ce este atmosfera?;Ce este hidrosfera?;Ce este litosfera?","Ce este biosfera?","Biodiversitate","Medie"),
(79,"Ecosistem afectat","Ce este degradarea mediului?;Ce este adaptarea?;Ce este evolutia?;Ce este migratia?","Ce este degradarea mediului?","Biodiversitate","Medie"),
(80,"Specii endemice","Ce sunt speciile endemice?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile migratoare?","Ce sunt speciile endemice?","Biodiversitate","Grea"),

(81,"Retea trofica","Ce este reteaua trofica?;Ce este lantul trofic?;Ce este ecosistemul?;Ce este habitatul?","Ce este reteaua trofica?","Biodiversitate","Grea"),
(82,"Extinctie in masa","Ce este extinctia in masa?;Ce este adaptarea?;Ce este migratia?;Ce este evolutia?","Ce este extinctia in masa?","Biodiversitate","Grea"),
(83,"Adaptarea organismelor","Ce este adaptarea?;Ce este extinctia?;Ce este migratia?;Ce este poluarea?","Ce este adaptarea?","Biodiversitate","Medie"),
(84,"Specii protejate","Ce sunt speciile protejate?;Ce sunt speciile invazive?;Ce sunt speciile domestice?;Ce sunt speciile comune?","Ce sunt speciile protejate?","Biodiversitate","Medie"),
(85,"Ecosistem","Ce este ecosistemul?;Ce este habitatul?;Ce este clima?;Ce este relieful?","Ce este ecosistemul?","Biodiversitate","Medie"),

(86,"Fotosinteza","Ce este fotosinteza?;Ce este respiratia?;Ce este digestia?;Ce este excretia?","Ce este fotosinteza?","Biodiversitate","Usoara"),
(87,"Pradatori","Ce sunt pradatorii?;Ce sunt erbivorele?;Ce sunt omnivorele?;Ce sunt bacteriile?","Ce sunt pradatorii?","Biodiversitate","Usoara"),
(88,"Consumatori","Ce sunt consumatorii?;Ce sunt producatorii?;Ce sunt descompunatorii?;Ce sunt bacteriile?","Ce sunt consumatorii?","Biodiversitate","Medie"),
(89,"Producatori","Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt descompunatorii?;Ce sunt pradatorii?","Ce sunt producatorii?","Biodiversitate","Medie"),
(90,"Descompunatori","Ce sunt descompunatorii?;Ce sunt producatorii?;Ce sunt consumatorii?;Ce sunt pradatorii?","Ce sunt descompunatorii?","Biodiversitate","Medie"),

(91,"Relatie mutualista","Ce este mutualismul?;Ce este parazitismul?;Ce este competitia?;Ce este pradarea?","Ce este mutualismul?","Biodiversitate","Medie"),
(92,"Relatie parazitara","Ce este parazitismul?;Ce este mutualismul?;Ce este competitia?;Ce este cooperarea?","Ce este parazitismul?","Biodiversitate","Medie"),
(93,"Relatie cooperare","Ce este cooperarea?;Ce este parazitismul?;Ce este competitia?;Ce este pradarea?","Ce este cooperarea?","Biodiversitate","Usoara"),
(94,"Relatie competitie","Ce este competitia?;Ce este mutualismul?;Ce este parazitismul?;Ce este pradarea?","Ce este competitia?","Biodiversitate","Usoara"),
(95,"Habitat natural","Ce este habitatul?;Ce este ecosistemul?;Ce este biosfera?;Ce este relieful?","Ce este habitatul?","Biodiversitate","Usoara"),

(96,"Ecosistem global","Ce este biosfera?;Ce este ecosistemul?;Ce este habitatul?;Ce este populatia?","Ce este biosfera?","Biodiversitate","Medie"),
(97,"Adaptare la mediu","Ce este adaptarea?;Ce este extinctia?;Ce este migratia?;Ce este evolutia?","Ce este adaptarea?","Biodiversitate","Medie"),
(98,"Lant trofic","Ce este lantul trofic?;Ce este ecosistemul?;Ce este biosfera?;Ce este habitatul?","Ce este lantul trofic?","Biodiversitate","Medie"),
(99,"Retea trofica","Ce este reteaua trofica?;Ce este lantul trofic?;Ce este ecosistemul?;Ce este habitatul?","Ce este reteaua trofica?","Biodiversitate","Grea"),
(100,"Echilibru natural","Ce este echilibrul ecologic?;Ce este poluarea?;Ce este urbanizarea?;Ce este industrializarea?","Ce este echilibrul ecologic?","Biodiversitate","Grea");